// generated by 'threeport-sdk gen' - do not edit

package v0

// Tabler allows custom table names for objects in the Threeport database.
type Tabler interface {
	TableName() string
}

// TableName sets the name of the table for the WireguardDefinition objects in the database.
func (WireguardDefinition) TableName() string {
	return "randalljohnson_us_v0_wireguard_definitions"
}

// TableName sets the name of the table for the WireguardInstance objects in the database.
func (WireguardInstance) TableName() string {
	return "randalljohnson_us_v0_wireguard_instances"
}
