// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	api_v0 "github.com/randalljohnson/wireguard-threeport-module/pkg/api/v0"
	config_v0 "github.com/randalljohnson/wireguard-threeport-module/pkg/config/v0"
	"net/http"
)

// outputDescribev0WireguardDefinitionCmd produces the plain description
// output for the 'tptctl describe wireguard-definition' command
func outputDescribev0WireguardDefinitionCmd(
	wireguardDefinition *api_v0.WireguardDefinition,
	wireguardDefinitionConfig *config_v0.WireguardDefinitionConfig,
	apiClient *http.Client,
	apiEndpoint string,
) error {
	// output describe details
	fmt.Printf(
		"* WireguardDefinition Name: %s\n",
		*wireguardDefinitionConfig.WireguardDefinition.Name,
	)
	fmt.Printf(
		"* Created: %s\n",
		*wireguardDefinition.CreatedAt,
	)
	fmt.Printf(
		"* Last Modified: %s\n",
		*wireguardDefinition.UpdatedAt,
	)

	return nil
}

// outputDescribev0WireguardInstanceCmd produces the plain description
// output for the 'tptctl describe wireguard-instance' command
func outputDescribev0WireguardInstanceCmd(
	wireguardInstance *api_v0.WireguardInstance,
	wireguardInstanceConfig *config_v0.WireguardInstanceConfig,
	apiClient *http.Client,
	apiEndpoint string,
) error {
	// output describe details
	fmt.Printf(
		"* WireguardInstance Name: %s\n",
		*wireguardInstanceConfig.WireguardInstance.Name,
	)
	fmt.Printf(
		"* Created: %s\n",
		*wireguardInstance.CreatedAt,
	)
	fmt.Printf(
		"* Last Modified: %s\n",
		*wireguardInstance.UpdatedAt,
	)

	return nil
}
