// generated by 'threeport-sdk gen' - do not edit

package notif

const (
	WireguardStreamName = "randalljohnson-us_wireguardStream"

	WireguardDefinitionSubject       = "randalljohnson-us_wireguardDefinition.*"
	WireguardDefinitionCreateSubject = "randalljohnson-us_wireguardDefinition.create"
	WireguardDefinitionUpdateSubject = "randalljohnson-us_wireguardDefinition.update"
	WireguardDefinitionDeleteSubject = "randalljohnson-us_wireguardDefinition.delete"

	WireguardInstanceSubject       = "randalljohnson-us_wireguardInstance.*"
	WireguardInstanceCreateSubject = "randalljohnson-us_wireguardInstance.create"
	WireguardInstanceUpdateSubject = "randalljohnson-us_wireguardInstance.update"
	WireguardInstanceDeleteSubject = "randalljohnson-us_wireguardInstance.delete"
)

// GetWireguardDefinitionSubjects returns the NATS subjects
// for wireguard definitions.
func GetWireguardDefinitionSubjects() []string {
	return []string{
		WireguardDefinitionCreateSubject,
		WireguardDefinitionUpdateSubject,
		WireguardDefinitionDeleteSubject,
	}
}

// GetWireguardInstanceSubjects returns the NATS subjects
// for wireguard instances.
func GetWireguardInstanceSubjects() []string {
	return []string{
		WireguardInstanceCreateSubject,
		WireguardInstanceUpdateSubject,
		WireguardInstanceDeleteSubject,
	}
}

// GetWireguardSubjects returns the NATS subjects
// for all wireguard objects.
func GetWireguardSubjects() []string {
	var wireguardSubjects []string

	wireguardSubjects = append(wireguardSubjects, GetWireguardDefinitionSubjects()...)
	wireguardSubjects = append(wireguardSubjects, GetWireguardInstanceSubjects()...)

	return wireguardSubjects
}
