// generated by 'threeport-sdk gen' - do not edit

package routes

import (
	echo "github.com/labstack/echo/v4"
	handlers "github.com/randalljohnson/wireguard-threeport-module/pkg/api-server/v0/handlers"
)

// AddRoutes adds routes for all objects of a particular API version.
func AddRoutes(e *echo.Echo, h *handlers.Handler) {
	WireguardDefinitionRoutes(e, h)
	WireguardInstanceRoutes(e, h)
}
