// generated by 'threeport-sdk gen' - do not edit

package routes

import (
	echo "github.com/labstack/echo/v4"
	handlers "github.com/randalljohnson/wireguard-threeport-module/pkg/api-server/v0/handlers"
	v0 "github.com/randalljohnson/wireguard-threeport-module/pkg/api/v0"
)

// WireguardDefinitionRoutes sets up all routes for the WireguardDefinition handlers.
func WireguardDefinitionRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathWireguardDefinitionVersions, h.GetWireguardDefinitionVersions)

	e.POST(v0.PathWireguardDefinitions, h.AddWireguardDefinition)
	e.GET(v0.PathWireguardDefinitions, h.GetWireguardDefinitions)
	e.GET(v0.PathWireguardDefinitions+"/:id", h.GetWireguardDefinition)
	e.PATCH(v0.PathWireguardDefinitions+"/:id", h.UpdateWireguardDefinition)
	e.PUT(v0.PathWireguardDefinitions+"/:id", h.ReplaceWireguardDefinition)
	e.DELETE(v0.PathWireguardDefinitions+"/:id", h.DeleteWireguardDefinition)
}

// WireguardInstanceRoutes sets up all routes for the WireguardInstance handlers.
func WireguardInstanceRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathWireguardInstanceVersions, h.GetWireguardInstanceVersions)

	e.POST(v0.PathWireguardInstances, h.AddWireguardInstance)
	e.GET(v0.PathWireguardInstances, h.GetWireguardInstances)
	e.GET(v0.PathWireguardInstances+"/:id", h.GetWireguardInstance)
	e.PATCH(v0.PathWireguardInstances+"/:id", h.UpdateWireguardInstance)
	e.PUT(v0.PathWireguardInstances+"/:id", h.ReplaceWireguardInstance)
	e.DELETE(v0.PathWireguardInstances+"/:id", h.DeleteWireguardInstance)
}
