// generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package wireguard

import (
	logr "github.com/go-logr/logr"
	v0 "github.com/randalljohnson/wireguard-threeport-module/pkg/api/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
)

// v0WireguardDefinitionCreated performs reconciliation when a v0 WireguardDefinition
// has been created.
func v0WireguardDefinitionCreated(
	r *controller.Reconciler,
	wireguardDefinition *v0.WireguardDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0WireguardDefinitionUpdated performs reconciliation when a v0 WireguardDefinition
// has been updated.
func v0WireguardDefinitionUpdated(
	r *controller.Reconciler,
	wireguardDefinition *v0.WireguardDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0WireguardDefinitionDeleted performs reconciliation when a v0 WireguardDefinition
// has been deleted.
func v0WireguardDefinitionDeleted(
	r *controller.Reconciler,
	wireguardDefinition *v0.WireguardDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
