// generated by 'threeport-sdk gen' - do not edit

package wireguard

// The name and description of the NATS bucket used for wireguard object locks
const (
	LockBucketName  = "wireguardLock"
	LockBucketDescr = "contains locks on wireguard objects"
)
