// generated by 'threeport-sdk gen' - do not edit

package wireguard

import (
	"errors"
	"fmt"
	api_v0 "github.com/randalljohnson/wireguard-threeport-module/pkg/api/v0"
	client_v0 "github.com/randalljohnson/wireguard-threeport-module/pkg/client/v0"
	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	tpclient_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	event "github.com/threeport/threeport/pkg/event/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
)

// WireguardInstanceReconciler reconciles system state when a WireguardInstance
// is created, updated or deleted.
func WireguardInstanceReconciler(r *controller.Reconciler) {
	r.ShutdownWait.Add(1)
	reconcilerLog := r.Log.WithValues("reconcilerName", r.Name)
	reconcilerLog.Info("reconciler started")
	shutdown := false

	// create a channel to receive OS signals
	osSignals := make(chan os.Signal, 1)
	lockReleased := make(chan bool, 1)

	// register the os signals channel to receive SIGINT and SIGTERM signals
	signal.Notify(osSignals, syscall.SIGINT, syscall.SIGTERM)

	for {
		// create a fresh log object per reconciliation loop so we don't
		// accumulate values across multiple loops
		log := r.Log.WithValues("reconcilerName", r.Name)

		if shutdown {
			break
		}

		// check for shutdown instruction
		select {
		case <-r.Shutdown:
			shutdown = true
		default:
			// pull message off queue
			msg := r.PullMessage()
			if msg == nil {
				continue
			}

			// consume message data to capture notification from API
			notif, err := notifications.ConsumeMessage(msg.Data)
			if err != nil {
				log.Error(
					err, "failed to consume message data from NATS",
					"msgData", string(msg.Data),
				)
				r.RequeueRaw(msg)
				log.V(1).Info("wireguard instance reconciliation requeued with identical payload and fixed delay")
				continue
			}

			// determine the correct object version from the notification
			var wireguardInstance tpapi_lib.ReconciledThreeportApiObject
			switch notif.ObjectVersion {
			case "v0":
				wireguardInstance = &api_v0.WireguardInstance{}
			default:
				log.Error(errors.New("received unrecognized version of wireguard instance object"), "")
				r.RequeueRaw(msg)
				log.V(1).Info("wireguard instance reconciliation requeued with identical payload and fixed delay")
				continue
			}

			// decode the object that was sent in the notification
			if err := wireguardInstance.DecodeNotifObject(notif.Object); err != nil {
				log.Error(err, "failed to marshal object map from consumed notification message")
				r.RequeueRaw(msg)
				log.V(1).Info("wireguard instance reconciliation requeued with identical payload and fixed delay")
				continue
			}
			log = log.WithValues("wireguardInstanceID", wireguardInstance.GetId())

			// back off the requeue delay as needed
			requeueDelay := controller.SetRequeueDelay(
				notif.CreationTime,
			)

			// check for lock on object
			locked, ok := r.CheckLock(wireguardInstance)
			if locked || ok == false {
				r.Requeue(wireguardInstance, requeueDelay, msg)
				log.V(1).Info("wireguard instance reconciliation requeued")
				continue
			}

			// set up handler to unlock and requeue on termination signal
			go func() {
				select {
				case <-osSignals:
					log.V(1).Info("received termination signal, performing unlock and requeue of wireguard instance")
					r.UnlockAndRequeue(wireguardInstance, requeueDelay, lockReleased, msg)
				case <-lockReleased:
					log.V(1).Info("reached end of reconcile loop for wireguard instance, closing out signal handler")
				}
			}()

			// put a lock on the reconciliation of the created object
			if ok := r.Lock(wireguardInstance); !ok {
				r.Requeue(wireguardInstance, requeueDelay, msg)
				log.V(1).Info("wireguard instance reconciliation requeued")
				continue
			}

			// retrieve latest version of object
			var latestWireguardInstance tpapi_lib.ReconciledThreeportApiObject
			var getLatestErr error
			switch notif.ObjectVersion {
			case "v0":
				latestObject, err := client_v0.GetWireguardInstanceByID(
					r.APIClient,
					r.APIServer,
					wireguardInstance.GetId(),
				)
				latestWireguardInstance = latestObject
				getLatestErr = err
			default:
				getLatestErr = errors.New("received unrecognized version of wireguard instance object")
			}

			// check if error is 404 - if object no longer exists, no need to requeue
			if errors.Is(getLatestErr, tpclient_lib.ErrObjectNotFound) {
				log.Info("object no longer exists - halting reconciliation")
				r.ReleaseLock(wireguardInstance, lockReleased, msg, true)
				continue
			}
			if getLatestErr != nil {
				log.Error(getLatestErr, "failed to get wireguard instance by ID from API")
				r.UnlockAndRequeue(wireguardInstance, requeueDelay, lockReleased, msg)
				continue
			}
			wireguardInstance = latestWireguardInstance

			// determine which operation and act accordingly
			switch notif.Operation {
			case notifications.NotificationOperationCreated:
				if wireguardInstance.ScheduledForDeletion() != nil {
					log.Info("wireguard instance scheduled for deletion - skipping create")
					break
				}
				var operationErr error
				var customRequeueDelay int64
				switch wireguardInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0WireguardInstanceCreated(
						r,
						wireguardInstance.(*api_v0.WireguardInstance),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of wireguard instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile created wireguard instance object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedCreate),
							Type:   util.Ptr(event.TypeNormal),
						},
						wireguardInstance.GetId(),
						wireguardInstance.GetVersion(),
						wireguardInstance.GetType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						wireguardInstance,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("create requeued for future reconciliation")
					r.UnlockAndRequeue(
						wireguardInstance,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationUpdated:
				var operationErr error
				var customRequeueDelay int64
				switch wireguardInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0WireguardInstanceUpdated(
						r,
						wireguardInstance.(*api_v0.WireguardInstance),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of wireguard instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile updated wireguard instance object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedUpdate),
							Type:   util.Ptr(event.TypeNormal),
						},
						wireguardInstance.GetId(),
						wireguardInstance.GetVersion(),
						wireguardInstance.GetType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						wireguardInstance,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("update requeued for future reconciliation")
					r.UnlockAndRequeue(
						wireguardInstance,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationDeleted:
				var operationErr error
				var customRequeueDelay int64
				switch wireguardInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0WireguardInstanceDeleted(
						r,
						wireguardInstance.(*api_v0.WireguardInstance),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of wireguard instance encountered for creation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile deleted wireguard instance object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedDelete),
							Type:   util.Ptr(event.TypeNormal),
						},
						wireguardInstance.GetId(),
						wireguardInstance.GetVersion(),
						wireguardInstance.GetType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						wireguardInstance,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("delete requeued for future reconciliation")
					r.UnlockAndRequeue(
						wireguardInstance,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				deletionTimestamp := util.Ptr(time.Now().UTC())
				deletedWireguardInstance := api_v0.WireguardInstance{
					Common: tpapi_v0.Common{ID: util.Ptr(wireguardInstance.GetId())},
					Reconciliation: tpapi_v0.Reconciliation{
						DeletionAcknowledged: deletionTimestamp,
						DeletionConfirmed:    deletionTimestamp,
						Reconciled:           util.Ptr(true),
					},
				}
				_, err = client_v0.UpdateWireguardInstance(
					r.APIClient,
					r.APIServer,
					&deletedWireguardInstance,
				)
				if err != nil {
					log.Error(err, "failed to update wireguard instance to mark as deleted")
					r.UnlockAndRequeue(wireguardInstance, requeueDelay, lockReleased, msg)
					continue
				}
				_, err = client_v0.DeleteWireguardInstance(
					r.APIClient,
					r.APIServer,
					wireguardInstance.GetId(),
				)
				if err != nil {
					log.Error(err, "failed to delete wireguard instance")
					r.UnlockAndRequeue(wireguardInstance, requeueDelay, lockReleased, msg)
					continue
				}
			default:
				log.Error(
					errors.New("unrecognized notifcation operation"),
					"notification included an invalid operation",
				)
				r.UnlockAndRequeue(
					wireguardInstance,
					requeueDelay,
					lockReleased,
					msg,
				)
				continue
			}

			// set the object's Reconciled field to true if not deleted
			if notif.Operation != notifications.NotificationOperationDeleted {
				reconciledWireguardInstance := api_v0.WireguardInstance{
					Common:         tpapi_v0.Common{ID: util.Ptr(wireguardInstance.GetId())},
					Reconciliation: tpapi_v0.Reconciliation{Reconciled: util.Ptr(true)},
				}
				updatedWireguardInstance, err := client_v0.UpdateWireguardInstance(
					r.APIClient,
					r.APIServer,
					&reconciledWireguardInstance,
				)
				if err != nil {
					log.Error(err, "failed to update wireguard instance to mark as reconciled")
					r.UnlockAndRequeue(wireguardInstance, requeueDelay, lockReleased, msg)
					continue
				}
				log.V(1).Info(
					"wireguard instance marked as reconciled in API",
					"wireguard instanceName", updatedWireguardInstance.Name,
				)
			}

			// release the lock on the reconciliation of the created object
			if ok := r.ReleaseLock(wireguardInstance, lockReleased, msg, true); !ok {
				log.Error(errors.New("wireguard instance remains locked - will unlock when TTL expires"), "")
			} else {
				log.V(1).Info("wireguard instance unlocked")
			}

			// log and record event for successful reconciliation
			successMsg := fmt.Sprintf(
				"wireguard instance successfully reconciled for %s operation",
				strings.ToLower(string(notif.Operation)),
			)
			if err := r.EventsRecorder.RecordEvent(
				&tpapi_v0.Event{
					Note:   util.Ptr(successMsg),
					Reason: util.Ptr(event.GetSuccessReasonForOperation(notif.Operation)),
					Type:   util.Ptr(event.TypeNormal),
				},
				wireguardInstance.GetId(),
				wireguardInstance.GetVersion(),
				wireguardInstance.GetType(),
			); err != nil {
				log.Error(err, "failed to record event for successful wireguard instance reconciliation")
			}
			log.Info(successMsg)
		}
	}

	r.Sub.Unsubscribe()
	reconcilerLog.Info("reconciler shutting down")
	r.ShutdownWait.Done()
}
