// generated by 'threeport-sdk gen' - do not edit

package versions

import (
	apiserver_v0 "github.com/randalljohnson/wireguard-threeport-module/pkg/api-server/v0"
	api_v0 "github.com/randalljohnson/wireguard-threeport-module/pkg/api/v0"
	tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	"reflect"
)

// AddWireguardDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddWireguardDefinitionVersions() {
	apiserver_v0.WireguardDefinitionTaggedFields[tpapiserver_lib.TagNameValidate] = &tpapiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              tpapiserver_lib.TagNameValidate,
	}

	// parse struct and populate the FieldsByTag object
	tpapiserver_lib.ParseStruct(
		tpapiserver_lib.TagNameValidate,
		reflect.ValueOf(new(api_v0.WireguardDefinition)),
		"",
		tpapiserver_lib.Translate,
		apiserver_v0.WireguardDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := tpapiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeWireguardDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	tpapiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.WireguardDefinitionTaggedFields[tpapiserver_lib.TagNameValidate]

	// add the object tagged fields to the rest API version
	tpapiserver_lib.AddObjectVersion(versionObj)
}

// AddWireguardInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddWireguardInstanceVersions() {
	apiserver_v0.WireguardInstanceTaggedFields[tpapiserver_lib.TagNameValidate] = &tpapiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              tpapiserver_lib.TagNameValidate,
	}

	// parse struct and populate the FieldsByTag object
	tpapiserver_lib.ParseStruct(
		tpapiserver_lib.TagNameValidate,
		reflect.ValueOf(new(api_v0.WireguardInstance)),
		"",
		tpapiserver_lib.Translate,
		apiserver_v0.WireguardInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := tpapiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeWireguardInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	tpapiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.WireguardInstanceTaggedFields[tpapiserver_lib.TagNameValidate]

	// add the object tagged fields to the rest API version
	tpapiserver_lib.AddObjectVersion(versionObj)
}
